import { NextResponse } from "next/server";
import {
    APP_NAME,
    APP_TAGLINE,
    APP_SUBTITLE,
    APP_DESCRIPTION,
    APP_TAGS,
    APP_CATEGORY,
    ROOT_URL,
} from "@/lib/constants";

export async function GET() {
    const manifest = {
        // Account Association - Signed by Base Build
        accountAssociation: {
            header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4NzAxYzI0NjUyQTM5MkU5RDRDRkJBNjNmNzk1REFGQTRlY0MzOEI2YSJ9",
            payload: "eyJkb21haW4iOiJuZW9uZG9kZ2UtbmluZS52ZXJjZWwuYXBwIn0",
            signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAlmA9FzHU_pSDpwYxE_uaYod6Z5UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB6E5rYGwFi7K2zW3tSb8n2WTCkBVHSn49CIMVZAbmkzh1_WjA0lEdth3sUHZ-3MKEFf7FvMIFrDjhUSgU_yK6WRsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI",
        },

        // Mini App Configuration
        miniapp: {
            version: "1",
            name: APP_NAME,
            subtitle: APP_SUBTITLE,
            description: APP_DESCRIPTION,
            tagline: APP_TAGLINE,
            homeUrl: ROOT_URL,
            iconUrl: `${ROOT_URL}/assets/icon.png`,
            splashImageUrl: `${ROOT_URL}/assets/splash.png`,
            splashBackgroundColor: "#0a0a0f",
            heroImageUrl: `${ROOT_URL}/assets/hero.png`,
            screenshotUrls: [
                `${ROOT_URL}/assets/screenshot-1.png`,
            ],
            primaryCategory: APP_CATEGORY,
            tags: APP_TAGS,
            ogTitle: `${APP_NAME} - ${APP_TAGLINE}`,
            ogDescription: APP_DESCRIPTION,
            ogImageUrl: `${ROOT_URL}/assets/hero.png`,
            // Ready for production
            noindex: false,
        },
    };

    return NextResponse.json(manifest, {
        headers: {
            "Content-Type": "application/json",
            "Cache-Control": "public, max-age=300",
        },
    });
}
